[package]
name = "serverstat"
description = "Query QuakeWorld servers for settings and client information."
keywords = ["servers", "quake", "quakeworld"]
repository = "https://github.com/quakeworld/serverstat"
authors = ["Viktor Persson <viktor.persson@arcsin.se>"]
version = "0.1.5"
edition = "2024"
license = "MIT"
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/src/**",
    "/tests/**",
]

[dependencies]
anyhow = "1.0.97"
hostport = { version = "0.1.0", features = ["json"] }
phf = { version = "0.11.3", features = ["macros"] }
quake_serverinfo = { version = "0.8.0", default-features = false, features = [] }
quake_text = "0.3.0"
thiserror = "2.0.11"
tinyudp = { version = "0.6.0", features=["tokio"] }

tokio = { optional = true, version = "1.44.1", features = ["macros"] }
serde = { optional = true, version = "1.0.219", features = ["derive"] }
serde_json = { optional = true, version = "1.0.140" }

[dev-dependencies]
pretty_assertions = "1.4.1"

[features]
ci = []
serde = ["dep:serde", "dep:serde_json", "quake_serverinfo/json"]
tokio = ["dep:tokio"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage,coverage_nightly)'] }
