name: Test

on:
  push:
    paths:
      - "src/**.rs"
      - "Cargo.*"
  pull_request:
    paths:
      - "src/**.rs"
      - "Cargo.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: "Build and test"
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack
      - uses: Swatinem/rust-cache@v2

      - name: Build all features
        run: cargo build --all-features

      - name: Build each feature
        run: cargo hack build --each-feature

      - name: Test all features
        run: cargo test --all-features

      - name: Test each feature
        run: cargo hack test --each-feature
